name: abstract_data_layer
description: An abstract data layer, simplify Firebase and Hive implementation
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: "^4.0.0"
  cloud_firestore: "^0.14.0+2"
  hive: "1.4.4"

  firebase_auth: "0.18.1+2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "4.1.2"

flutter:

